id: P1C3F837F
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: en
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    854b482ee3804e4d9d28b4cc67171ea9:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    f101e46df3b846eb82c108ea692aba13:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    27a9ed48dd8f42189042b3591f2b1a7b:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    c998865255e74ac58011987ebb0712ac:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    0e83778341374836895a4c2ad6d48d75:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    74b5ac49276743cdaa0825c74b0db8d4:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    efdb4f611e0140d6840ed99e094f4c93:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    b9bfe4f5e4384e858887ac11dda1793d:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    0bfd3c78a802421abc3355899603893d:
      title: The Lament of Rudra
      parent: Confession
    a440baf263634a95992685a02bfacbd8:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    4fa4e187ac584cd0b96837347236eef3:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    b83dcb76f44b48b1b2a8f11b19f215a0:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    85619402d51f463ab41edaa0c8b765fb:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    f774044b27a54cdf9ac9b9e6e99fb79f:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    62f75f51b66141da9759d815cc6f5a78:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    385ff427579847b69327b5259578c6b9:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    96631e96bc74490a9914775fec65513c:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    32c21b5650e241ea97bc0f7c34c70a82:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    dcbf0d303fb24ab68125ba02e20020d8:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.990911'
last_modified_at: '2022-03-01T03:13:53.990917'
